stages:
  - build

build:
  image: docker:19.03.12
  only:
    - tags
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/giovanni-liboni/docker-univrnews-dev:$CI_COMMIT_TAG .
    - docker push registry.gitlab.com/giovanni-liboni/docker-univrnews-dev:$CI_COMMIT_TAG
